- name: Installation von Paketupdates
  hosts: Testgruppe
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: yes
    register: upgrade_output

  - name: Remove unused packages
    apt:
      autoremove: yes