- name: Installation von Paketupdates
  hosts: all
  become: true

  pre_tasks:
    - name: Run tasks as root user
      become_user: root
      shell: "sudo bash"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
      register: upgrade_output

    - name: Remove unused packages
      apt:
        autoremove: yes

    - name: Reboot the server
      reboot:
        reboot_timeout: 300
        post_reboot_delay: 60
        test_command: uptime
      async: 0
      poll: 0
      ignore_errors: true
      register: reboot_result

    - name: Wait for the server to come back
      wait_for_connection:
        delay: 10
        timeout: 600
      when: reboot_result is succeeded

    - name: Ping test to check if server is up
      ping:
      when: reboot_result is succeeded

    - name: Mark success if the server was rebooted successfully
      debug:
        msg: "Der Job wurde erfolgreich durchgeführt."
      when: reboot_result is succeeded