- name: Installation von Security Updates mit Reboot
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade Sicherheitsupdates
      apt:
        security_upgrade: yes
      register: upgrade_output

    - name: Reboot the server
      reboot:
        reboot_timeout: 300
        post_reboot_delay: 60
        test_command: uptime
      register: reboot_result

    - name: Wait for the server to come back
      wait_for_connection:
        delay: 10
        timeout: 600
      when: reboot_result is succeeded

    - name: Ping test to check if server is up
      ping:
      when: reboot_result is succeeded

    - name: Mark success if the server was rebooted successfully
      debug:
        msg: "The server was rebooted successfully."
      when: reboot_result is succeeded

    - name: Send email notification on successful reboot
      command: "echo 'Reboot was successful.{{ upgrade_output.stdout_lines | to_nice_yaml }}\n\n{{ reboot_result.stdout_lines | to_nice_yaml }}' | mail -s 'Ansible Job Status - Success' -a 'From: ansible@becksche.de' -r ansible@becksche.de schoeppl.nico@becksche.de"
      args:
        executable: /usr/sbin/sendmail
      delegate_to: 10.200.1.115
      when: reboot_result is succeeded

    - name: Send email notification on failed reboot
      command: "echo 'Reboot failed.{{ upgrade_output.stdout_lines | to_nice_yaml }}\n\n{{ reboot_result.stdout_lines | to_nice_yaml }}' | mail -s 'Ansible Job Status - Failed' -a 'From: ansible@becksche.de' -r ansible@becksche.de schoeppl.nico@becksche.de"
      args:
        executable: /usr/sbin/sendmail
      delegate_to: 10.200.1.115
      when: reboot_result|failed
