- name: Test-Mailversand
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Sende Test-E-Mail
      command: "echo 'Dies ist eine Test-E-Mail von Ansible' | /usr/sbin/sendmail -s 'Test-E-Mail von Ansible' -a 'From: ansible@becksche.de' -r ansible@becksche.de sysadmins@becksche.de"
