- name: Installation von Security Updates
  hosts: Ubuntu Server
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: safe
    register: upgrade_output

  - name: Remove unused packages
    apt:
      autoremove: yes